server:
  port: 9001
  servlet:
    context-path: /auth

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/b12_auth_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
     ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    service-registry:
      auto-registration:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

jwt:
  secret-key: 6LmeVJfpwtyRj9YBNLXmV8JozlbMOg2g