server:
  port: 9005
  servlet:
    context-path: /product

spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/b12_prod_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka